apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: secondmeshapp
spec:
  hosts:
    - secondmeshapp.apps.cluster-z9nwc.z9nwc.sandbox439.opentlc.com
  gateways:
    - mesh-gateway
  http:
    - match:
        - uri:
            exact: /secondmeshapp
        - uri:
            exact: /bla
      route:
        - destination:
            host: secondmeshapp
            port:
              number: 9090
